const familiars= [
    {
        familiarName: "Crawling Familiar",
        size: "Tiny",
        type: "Beast",
        typeFlavor: " (Occult or Primal)",
        str: -2,
        dex: 3,
        ref: 13,
        end: 0,
        fort: 10,
        awr: 1,
        ant: 11,
        intellegence: -3,
        logistics: 7,
        charisma: -2,
        will: 8,
        movement: {
            walk: 20,
            climb: 20,
            swim: 0,
            fly: 0,
        },
        senses: { darkvision: 30 },
        skills:[],
        Actions: [
            { actionName: "Frightening", description: "When your familiar is within 5 ft of you, you gain Intimidating +4." },
            { actionName: "Spy", description: "You can magically see through your familiar’s eyes for a brief moment, provided that your familiar is within 500 ft of you." },
            { actionName: "Ward", description: "If your familiar is within 5 ft of you, it protectively crouches nearby. The next time you take damage from another creature before the start of your next turn (providedthat you are still within 5 ft of your familiar), reduce the damage by 1d4 + your Witch level." },
        ],
    },
    {
    familiarName: "",
    size: "",
    type: "",
    typeFlavor: "",
    str: 0,
    dex: 0,
    ref: 0,
    end: 0,
    fort: 0,
    awr: 0,
    ant: 0,
    intellegence: 0,
    logistics: 0,
    charisma: 0,
    will: 0,
    movement: {
        walk: 20,
        climb: 0,
        swim: 0,
        fly: 0,
    },
    senses: { darkvision: 0,  },
    skills:[
        
        {stat:"AWR", skillName:"Perceiving", score:3},
        {stat:"AWR", skillName:"Tracking", score:3},
    ],
    Actions: [
        { actionName: "", description: "" },
        { actionName: "", description: "" },
        { actionName: "", description: "" },
    ],
},
{
familiarName: "",
size: "",
type: "",
typeFlavor: "",
str: 0,
dex: 0,
ref: 0,
end: 0,
fort: 0,
awr: 0,
ant: 0,
intellegence: 0,
logistics: 0,
charisma: 0,
will: 0,
movement: {
    walk: 20,
    climb: 0,
    swim: 0,
    fly: 0,
},
senses: { darkvision: 0,  },
skills:[
    
    {stat:"AWR", skillName:"Perceiving", score:3},
    {stat:"AWR", skillName:"Tracking", score:3},
],
Actions: [
    { actionName: "", description: "" },
    { actionName: "", description: "" },
    { actionName: "", description: "" },
],
},
{
familiarName: "",
size: "",
type: "",
typeFlavor: "",
str: 0,
dex: 0,
ref: 0,
end: 0,
fort: 0,
awr: 0,
ant: 0,
intellegence: 0,
logistics: 0,
charisma: 0,
will: 0,
movement: {
    walk: 20,
    climb: 0,
    swim: 0,
    fly: 0,
},
senses: { darkvision: 0,  },
skills:[
    
    {stat:"AWR", skillName:"Perceiving", score:3},
    {stat:"AWR", skillName:"Tracking", score:3},
],
Actions: [
    { actionName: "", description: "" },
    { actionName: "", description: "" },
    { actionName: "", description: "" },
],
},

];