mcStandardProfessions = [
    {
        name: { noun: "Sailor", },
        occupations: ["Mercantile", "Underworld", "Wanderer"],
        description: "You have spent considerable time as an explorer, freebooter, pirate or mariner and define your life by the sea. From skiffs to frigates, you know your way around a ship and are as comfortable in a raging storm as you are in a pleasant breeze. You embrace the freedom, adventure, and danger of life as you traverse the trading lanes or explore parts unknown, never knowing what might be waiting over the next wave.",
        StartingEquipment: [
            { name: "rucksack", qty: 1, canChoose: false, type: "mundane" },
            { name: "leather armor", qty: 1, canChoose: false, type: "mundane" },
            { name: "Choose a tool or kit", qty: 1, canChoose: false, type: "mundane" },
            { name: "clothes (simple)", qty: 1, canChoose: true, type: "tool or kit" },
            { name: "mess kit,", qty: 1, canChoose: false, type: "mundane" },
            { name: "rations", qty: 5, canChoose: false, type: "mundane" },
            { name: "utensils", qty: 1, canChoose: false, type: "mundane" },
            { name: "bowl", qty: 1, canChoose: false, type: "mundane" },
            { name: "flask", qty: 1, canChoose: false, type: "mundane" },
            { name: "50 ft rope", qty: 2, canChoose: false, type: "mundane" },
            { name: "compass", qty: 1, canChoose: false, type: "mundane" },
        ],
        skillsEachRank: {
            skills: [
                { name: "Acrobatics", requiresTools: true, options: ["Balancing"] },
                { name: "Athleticism", requiresTools: true, options: ["Applied Force, Athletics"] },
                { name: "Crafting*", requiresTools: true, options: ["Cartography, Cooking", "Woodcarving"] },
                { name: "Influence", requiresTools: false, options: ["Intimidating, Leadership"] },
                { name: "Knowledge", requiresTools: true, options: ["Astrology, Astronomy, Geography,Economics, Medicine *, Military"] },
                { name: "Lucky", requiresTools: false, options: ["Fortuity, Scavenging"] },
                { name: "Observation", requiresTools: true, options: ["Intuiting", "Perceiving"] },
                { name: "Performance", requiresTools: true, options: ["Instrument* [choose one], Singing"] },
                { name: "Stamina", requiresTools: true, options: ["Menacing", "Swimming"] },
                { name: "Subterfuge", requiresTools: true, options: ["Evading", "Sleight of Hand"] },
                { name: "Survival", requiresTools: true, options: ["Nature, Navigating*"] },
            ],
            rankingBlerb: "",

            occupationBonus: "",
            startingWealth: { roll: "", average: 100, },
            ranking: {
                noun: "Sea legs",
                specializations: ["", ""],
                description: "When you become a rank 1 Sailor, and every time you gain a rank in the Sailor profession, your reputation among NPCs with your choice of mercantile, military, or underworld backgrounds improves.",
                ranksAndSpecializations: [

                    {
                        rank: 1,
                        prerequisite: { rank: 0, specialization: "Crewmate" },
                        specializationTitle: "Crewmate",
                        description: ": You have the skills and knowledge to secure a temporary position on a trading, privateer, pirate, or exploratory vessel and earn 10 sc for every week spent working in a friendly port.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 2,
                        prerequisite: { rank: 1, specialization: "Boatswain" },
                        specializationTitle: "Boatswain",
                        description: "You are an established member of a ship’s crew that provides you with free room and board in any port in which the ship is docked. You now earn 15 sc for every week of service, even if you are not at a port.",
                        canChooseSpecialization: false,
                    }, {
                        rank: 3,
                        prerequisite: { rank: 2, specialization: "Captain" },
                        specializationTitle: "Captain",
                        description: "You have risen to the rank of captain and have your own ship with a crew under your employ.When achieving rank 3 in this profession you may choose a specialization: explorer, merchant, pirate, or privateer.This choice grants you specific abilities at ranks 4 and 5 as well as this rank.",
                        canChooseSpecialization: true,
                    },
                    {
                        rank: 3,
                        prerequisite: { rank: 3, specialization: "Explorer" },
                        specializationTitle: "Explorer",
                        description: "When choosing this specialization, you may immediately gain 1 rank of the Nomad profession, including all starting equipment and skills.Your ship is outfitted for long journeys.Once per week you may attempt a short expedition to discover parts unknown.Roll a d10 and refer to the chart below. 1-4: Your expedition proves a failure and you are unable to discover any landmasses or treasure of note. 5-8: Your expedition uncovers an island or shipwreck. Selling the mapped location or recovered salvage earns you 4d10 sc. 9-10: You discover a valuable shipwreck or island teeming with resources.Selling the mapped location or recovered salvage earns you 4d10 + 40 sc.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 3,
                        prerequisite: { rank: 4, specialization: "Merchant" },
                        specializationTitle: "Merchant",
                        description: "When choosing this specialization you may immediately gain 1 rank of the Trader profession, including all equipment and skills.Every week you may perform a trade mission and earn 2d10 sc in addition to your trader income. When entering a new port, you can locate any specific shops, services, or trading houses within one hour.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 3,
                        prerequisite: { rank: 5, specialization: "Pirate" },
                        specializationTitle: "Pirate",
                        description: "When choosing this specialization you may immediately gain 1 rank of the Thug profession, including all equipment and skills.Once per week you may take your ship out to plunder a trading lane, earning you 8d10 + 80 sc but drawing the attention of local authorities.Every week spent plundering this region will earn your ship a cumulative 50 sc bounty that increases the chance of direct conflict with military or privateer vessels. You become aware of one safe port in the region that will never attempt to collect your bounty.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 3,
                        prerequisite: { rank: 6, specialization: "Privateer" },
                        specializationTitle: "Privateer",
                        description: "When choosing this specialization you may immediately gain 1 rank of the Soldier profession, including all equipment and skills.Your ship and crew are well known to the military of your home region and you may accept military contracts.These contracts pay 4d10 sc and generally include providing escort for supply ships, hunting dangerous pirates, or protecting endangered ports.Each completed contract provides + 1 Goodwill with local settlements.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 4,
                        prerequisite: { rank: 1, specialization: "Explorer" },
                        specializationTitle: "Explorer",
                        description: "You are now an expedition leader and can attempt to fund more elaborate exploratory missions.These missions can be sponsored by NPCs with an academic or aristocratic background or can be paid out of your own pocket.Each sponsor gives you a + 1 on the Elaborate Expedition, but takes 10 % of final earnings.Failing to succeed may damage your reputation with your sponsor. You also gain 1 rank in the nomad profession. Elaborate Expedition: 1 - 4: Your expedition proves a failure and you are unable to discover any landmasses or treasure of note. 5 - 8: Your expedition uncovers an island or shipwreck. Selling the mapped location or recovered salvage earns you 8d10 sc.9-10: You discover a valuable shipwreck or island teeming with resources.Selling the location or recovered salvage earns you 8d10 + 80 sc.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 4,
                        prerequisite: { rank: 1, specialization: "Merchant" },
                        specializationTitle: "Merchant",
                        description: "You are now a company merchant and gain 1 rank in the trader profession. You may hire an additional ship and no longer need to be present on board to run a trade mission.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 4,
                        prerequisite: { rank: 2, specialization: "Pirate" },
                        specializationTitle: "Pirate",
                        description: "You are now a pirate master and have a second ship under your command.Your plunder now earns you 12d10 + 120 sc. You now know the location of every safe port and harbor within your home region and can spend one week discovering one in new regions you visit.Additionally, you gain 1 rank in the thug profession.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 4,
                        prerequisite: { rank: 3, specialization: "Privateer" },
                        specializationTitle: "Privateer",
                        description: "You are now a commodore and have outfitted your ship for serious military engagements. You may now take contracts to hunt down dangerous bounties.Completing these contracts pays 8d10 sc and earns you an audience with any official with the aristocratic or military background if they have 4 or fewer professional ranks.Additionally, you gain 1 rank in the Soldier profession.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 5,
                        prerequisite: { rank: 1, specialization: "Explorer" },
                        specializationTitle: "Explorer",
                        description: "You are now a famed explorer and your name is spoken with awe by NPCs with academic or aristocracy backgrounds. You are twice as likely to find sponsors among these groups. The next elaborate exploratory mission you successfully complete will result in a small landmass being named after you and will earn you double the associated payment. Additionally, you gain the ability to communicate rudimentary ideas to any intelligent beings, even if you do not speak their language, and gain a + 3 to Intuiting checks regarding understanding unknown cultures, customs, or languages.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 5,
                        prerequisite: { rank: 2, specialization: "Merchant" },
                        specializationTitle: "Merchant",
                        description: "You are now a company master and may employ up to three trading vessels.Additionally, you gain 1 rank in the Trader profession.",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 5,
                        prerequisite: { rank: 3, specialization: "Pirate" },
                        specializationTitle: "Pirate",
                        description: "You are now a pirate lord and may have a total of three ships in your fleet.Your plunder now earns you 20d10 + 200 sc and your infamy causes all but the bravest merchants to surrender without defense. You have a + 3 Intimidating against anyone within 5 miles of the port in which your ships are docked",
                        canChooseSpecialization: false,
                    },
                    {
                        rank: 5,
                        prerequisite: { rank: 4, specialization: "Privateer" },
                        specializationTitle: "Privateer",
                        description: "You are now an admiral in your home region’s navy and captain one of the strongest ships of the line available. You gain 1 rank in the Honorable profession, including all equipment and skills.",
                        canChooseSpecialization: false,
                    }
                ],
            }
        },
    }
    {
        name: {
            noun: "Soldier",
        },
        occupations: ["Militant"],
        description: "You are a proud and dedicated warrior, serving your country and your people with honor and distinction.From defending your homeland against invaders to marching on a foreign land for just war, you are always ready to put your life on the line in the name of duty and honor.With your training, your discipline, and your courage, you are a force to be reckoned with, feared by your enemies and respected by your allies, and you are proud to serve as a symbol of strength and protection for those you hold dear.",
        StartingEquipment: [
            { name: "rucksack", qty: 1, canChoose: false, type: "mundane" },
            { name: "spear or halberd", qty: 1, canChoose: false, type: "mundane" },
            { name: "Gambeson Armor", qty: 1, canChoose: false, type: "mundane" },
            { name: "chainmail armor", qty: 1, canChoose: true, type: "tool or kit" },
            { name: "clothes (simple)", qty: 1, canChoose: false, type: "mundane" },
            { name: "torches", qty: 5, canChoose: false, type: "mundane" },
            { name: "flask", qty: 1, canChoose: false, type: "mundane" },
            { name: "bedroll", qty: 1, canChoose: false, type: "mundane" },
            { name: "flint & steel", qty: 1, canChoose: false, type: "mundane" },
            { name: "insignia of rank (banner, patch,pin, etc.)", qty: 1, canChoose: false, type: "mundane" },
            { name: "rations ", qty: 7, canChoose: false, type: "mundane" },
            { name: "waterskin", qty: 1, canChoose: false, type: "mundane" },
            { name: "bandages", qty: 2, canChoose: false, type: "mundane" },
            { name: "50 ft rope", qty: 1, canChoose: false, type: "mundane" },
        ],
        skillsEachRank: {
            skills: [
                { name: "Acrobatics", requiresTools: true, options: ["Balancing"] },
                { name: "Athleticism", requiresTools: true, options: ["Applied Force, Athletics, Sprinting"] },
                { name: "Crafting*", requiresTools: true, options: ["Carpentry, Leatherworking", "Smithing,Woodcarving"] },
                { name: "Influence", requiresTools: false, options: ["Gossiping", "Intimidating, Leadership"] },
                { name: "Knowledge", requiresTools: true, options: ["Geography, History", "Law", "Medicine*, Military, Politics of[choose region], Religion [choose one], Vehicles * [land]"] },
                { name: "Observation", requiresTools: true, options: ["Intuiting", "Perceiving"] },
                { name: "Stamina", requiresTools: true, options: ["Forced March, Menacing"] },
                { name: "Survival", requiresTools: true, options: ["Animal Handling, Dungeoneering, Nature, Navigating * "] },
            ],
            rankingBlerb: "",
        },
        occupationBonus: "",
        startingWealth: { roll: "", average: 100, },
        ranking: {
            noun: "Military Ranking",
            specializations: ["", ""],
            description: "When you become a rank 1 Soldier, and every time you gain a rank in the Soldier profession, you advance your official position in the military entity of which you are a member.",
            ranksAndSpecializations: [

                {
                    rank: 1,
                    prerequisite: { rank: 0, specialization: "" },
                    specializationTitle: "",
                    description: "When you become a rank 1 Soldier, and every time you gain a rank in the Soldier profession, you advance your official position in the military entity of which you are a member.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 2,
                    prerequisite: { rank: 1, specialization: "" },
                    specializationTitle: "",
                    description: "You are a low-ranking noncommissioned (noncom) officer in the infantry In addition to your rank 1 benefits, while you are in an urban or rural area where your military maintains a presence, you gain a + 2 bonus to knowledge checks pertaining to current information of that region.Your stipend increases to 10 sc per week.",
                    canChooseSpecialization: false,
                }, {
                    rank: 3,
                    prerequisite: { rank: "", specialization: "" },
                    specializationTitle: "",
                    description: "When you reach rank 3 in the Soldier profession you may choose one of the specializations below: Infantry or Tactician.This choice gives you benefits at this rank, as well as ranks 4 and 5. Your stipend is now 15 sc per week.",
                    canChooseSpecialization: true,
                },
                {
                    rank: 3,
                    prerequisite: { rank: 1, specialization: "Infantry" },
                    specializationTitle: "Infantry",
                    description: "You are a mid-ranking noncom officer in the infantry. In addition to your rank 1 and 2 benefits, you can levy 2 members of your military that are Monster Level 2 or lower, such as Guards or Scouts.These members of the infantry will travel with you and fight to protect you while within 30 miles of their original post.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 3,
                    prerequisite: { rank: 1, specialization: "Tactician" },
                    specializationTitle: "Tactician",
                    description: "You are a recognized battlefield tactician and commander. Members of the military you serve gain + 1 to their WILL while you are within 30 ft of them and they can see you. The knowledge bonus of your rank 2 feature increases from + 2 to + 5.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 4,
                    prerequisite: { rank: 1, specialization: "Infantry" },
                    specializationTitle: "Infantry",
                    description: "You are a high-ranking noncom officer in the infantry. You can now levy 5 members of your military, instead of only 2, using your rank 3 feature. Additionally, you may spend one week joining the forces of your military on campaign or patrol.Doing so earns you an additional 2d10 sc per week as well as increasing your reputation.NPCs with the aristocratic or militant occupation and 4 or fewer professional ranks will make time to meet with you within 8 hours of your request. Your standard military stipend increases to 20 sc per week.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 4,
                    prerequisite: { rank: 2, specialization: "Tactician" },
                    specializationTitle: "Tactician",
                    description: "You are a distinguished battlefield tactician and commander. Any members of the military you serve gain + 1 to all of their mental defenses while they can see you and are within 30 ft of you.The knowledge bonus of your rank 3 feature increases from + 5 to + 7. Your standard military stipend increases to 20 sc per week.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 5,
                    prerequisite: { rank: "", specialization: "Infantry" },
                    specializationTitle: "Infantry",
                    description: "You are the highest rank of noncom officer in the infantry. You can now levy ten members of your military to travel with you anywhere within 30 miles of their original post. These NPCs can be of Monster Level 3 or lower.Additionally, you may spend one week joining the forces of your military on campaign or patrol.Doing so earns you an additional 4d10 sc per week. Your standard military stipend increases to 25 sc per week.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 5,
                    prerequisite: { rank: 4, specialization: "Tactician" },
                    specializationTitle: "Tactician",
                    description: "You are one of the most renowned military tacticians in the world and the knowledge bonus from your rank 4 feature increases from + 7 to + 10. Military commanders will seek you out for service and you may spend one week on campaign to earn 4d10 sc in payment. Furthermore, you can secure an audience with most military individuals of great influence.Any NPC with the equivalent of 5 or fewer ranks in any militant, aristocratic, or mercantile background will make time to meet with you within 2 hours of your request. Your standard military stipend increases to 25 sc per week.",
                    canChooseSpecialization: false,
                }
            ],
        }
    },
    {
        name: {
            noun: "Trader",
        },
        occupations: ["Mercantile"],
        description: "You are constantly on the move, traveling from town to town and village to village in search of new markets and opportunities.With a keen eye for profit and a talent for negotiation, you buy low and sell high, always seeking out the best deals and the most valuable merchandise to trade.Whether you are trading in exotic spices, rare herbs, precious gems, or any other commodity that you can get your hands on, you are always seeking to turn a profit and to grow your wealth and influence in the world.",
        StartingEquipment: [
            { name: "traveler’s pack", qty: 1, canChoose: false, type: "mundane" },
            { name: "hanging lantern rod", qty: 1, canChoose: false, type: "mundane" },
            { name: "gambeson armor", qty: 1, canChoose: false, type: "mundane" },
            { name: "Choose a tool or kit", qty: 1, canChoose: true, type: "tool or kit" },
            { name: "clothes(fine)", qty: 1, canChoose: false, type: "mundane" },
            { name: "blanket", qty: 1, canChoose: false, type: "mundane" },
            { name: "bedroll", qty: 1, canChoose: false, type: "mundane" },
            { name: "folding chair", qty: 1, canChoose: false, type: "mundane" },
            { name: "scales", qty: 1, canChoose: false, type: "mundane" },
            { name: "various pouches and bottles", qty: 2, canChoose: false, type: "mundane" },
            { name: "magnifying lens", qty: 1, canChoose: false, type: "mundane" },
            { name: "bolt of fabric (silk)", qty: 1, canChoose: false, type: "mundane" },
            { name: "spices (exotic) ", qty: 1, canChoose: false, type: "mundane" },
        ],
        skillsEachRank: {
            skills: [
                { name: "Crafting", requiresTools: true, options: ["Alchemy, Brewing", "Calligraphy, Carpentry", "Cartography", "Cobbling", "Cooking, Glassblowing, Jeweling, Leatherworking, Masonry, Painting", "Pottery, Smithing", "Weaving", "Woodcarving"] },
                { name: "Influence", requiresTools: false, options: ["Deceiving", "Empathy, Gossiping", "Persuading"] },
                { name: "Knowledge", requiresTools: false, options: ["Art", "Economics", "History", "Law", "Medicine*, Politics of[choose region], Vehicles*[land], Vehicles* [water]"] },
                { name: "Observation", requiresTools: false, options: ["Appraising", "Intuiting", "Perceiving"] },
                { name: "Survival", requiresTools: false, options: ["Animal Handling"] },
            ],
            rankingBlerb: "",
        },
        occupationBonus: "",
        startingWealth: { roll: "", average: 100, },
        ranking: {
            noun: "Network",
            specializations: ["", ""],
            description: "When you become a rank 1 Trader, and every time you gain a rank in the Trader profession, you can sell wares, resupply your stock, and expand your wealth and mercantile influence.",
            ranksAndSpecializations: [

                {
                    rank: 1,
                    prerequisite: { rank: 0, specialization: "" },
                    specializationTitle: "",
                    description: "Given one week of business dealings in a marketplace, you increase your profitability through skillful trade. You earn2d10 + 20 sc each time you do this.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 2,
                    prerequisite: { rank: 1, specialization: "" },
                    specializationTitle: "",
                    description: "Given one week of business dealings in a marketplace, you increase your profitability through skillful trade. You earn 4d10 + 20 sc each time you do this, and you gain one tool or kit of your choice, which you may sell for 20 additional sc or keep for your own uses.",
                    canChooseSpecialization: false,
                }, {
                    rank: 3,
                    prerequisite: { rank: 2, specialization: "" },
                    specializationTitle: "",
                    description: "In addition to your rank 2 benefits, you gain the entrepreneurial capacity to open satellite trading stalls under your personal brand.Pick three marketplaces that you have been to before: whenever you return to those marketplaces, you get food and lodging for free. Additionally, you only need three days of trade in those marketplaces to gain your rank 2 trader benefit.",
                    canChooseSpecialization: true,
                },
                {
                    rank: 4,
                    prerequisite: { rank: "", specialization: "" },
                    specializationTitle: "",
                    description: "You can apply your rank 3 benefit to any new marketplace that you travel to, provided that you spend at least one full week trading and establishing business connections in the new marketplace. Additionally, your rank 2 benefits increase to 8d10 + 80 sc and three tools or kits of your choice.",
                    canChooseSpecialization: false,
                },
                {
                    rank: 5,
                    prerequisite: { rank: 1, specialization: "" },
                    specializationTitle: "",
                    description: "Your reputation allows you to quickly ingratiate yourself into new marketplaces. You only need one day, rather than one week, to gain your rank 3 benefits in a new marketplace. Additionally, your rank 4 benefits increase to 15d10 + 150 sc and five tools or kits of your choice. Furthermore, as one of the most renowned entrepreneurs in the world, you can secure an audience with most individuals of great influence.Any NPC with the equivalent of 4 or fewer ranks in any occupation will make time to meet with you within 24 hours of your request.",
                    canChooseSpecialization: false,
                },
            ],
        }
    },];