const  Stanzas=[ 
    {stanzaName:"Antagonism", rank:[ "Scorn: Creature is Taunted by you.", "Range is 120 ft.", "Range is 120 ft, target two"]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
    {stanzaName:"", rank:[ "", "", ""]},
];

