const tinkeringItems=[
    {itemNmae:"Anti-Burglary Trigger",TinkeringCost:100, Uses:NaN, Description:"Apply this mod to a weapon. Anyone that attempts to wield that weapon and is unaware of the trigger must make a DC 20 AWR check. On a fail, they take 3d6 corrosive damage as acid and paint spray over them.", type:"general"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
    {itemNmae:"",TinkeringCost:1, Uses:1, Description:"", type:"general/special/ammo/alchemicl/thrown"},
];


 